import type { Level } from '../types/game';

export const WORLDS = [
  {
    id: 1,
    name: 'Pulau 1: Langkah Pertama',
    subtitle: 'Belajar Arah & Urutan Langkah (Sekuensi)',
    color: 'emerald',
    icon: '🌱',
    themeBg: 'from-emerald-50 to-teal-50',
    borderColor: 'border-emerald-300',
    accentColor: '#10b981',
  },
  {
    id: 2,
    name: 'Pulau 2: Lingkaran Ajaib',
    subtitle: 'Belajar Perulangan Praktis (Looping)',
    color: 'amber',
    icon: '🔄',
    themeBg: 'from-amber-50 to-orange-50',
    borderColor: 'border-amber-300',
    accentColor: '#f59e0b',
  },
  {
    id: 3,
    name: 'Pulau 3: Rintangan Cerdik',
    subtitle: 'Tantangan Logika & Lompatan Petualang',
    color: 'indigo',
    icon: '👑',
    themeBg: 'from-indigo-50 to-purple-50',
    borderColor: 'border-indigo-300',
    accentColor: '#6366f1',
  },
];

export const LEVELS: Level[] = [
  // PULAU 1: LANGKAH PERTAMA (Sekuensi Dasar)
  {
    id: 1,
    worldId: 1,
    worldName: 'Pulau Langkah Pertama',
    worldColor: 'emerald',
    title: 'Langkah Awal si Kiko',
    description: 'Bantu Kiko berjalan lurus menuju bendera finish!',
    hint: 'Pasang balok "Maju" sebanyak 2 kali, lalu tekan tombol Jalankan Kode 🚀.',
    gridWidth: 4,
    gridHeight: 4,
    startPos: { x: 1, y: 3 },
    startDir: 'NORTH',
    targetPos: { x: 1, y: 1 },
    stars: [{ x: 1, y: 2 }],
    obstacles: [],
    maxBlocks: 4,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
  },
  {
    id: 2,
    worldId: 1,
    worldName: 'Pulau Langkah Pertama',
    worldColor: 'emerald',
    title: 'Tikungan Ceria',
    description: 'Kiko harus berbelok ke kanan untuk mengambil bintang berkilau!',
    hint: 'Maju dulu 1 langkah, belok ke kanan, lalu maju lagi 1 langkah!',
    gridWidth: 4,
    gridHeight: 4,
    startPos: { x: 1, y: 2 },
    startDir: 'NORTH',
    targetPos: { x: 2, y: 1 },
    stars: [{ x: 1, y: 1 }, { x: 2, y: 1 }],
    obstacles: [{ x: 1, y: 0 }],
    maxBlocks: 5,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
  },
  {
    id: 3,
    worldId: 1,
    worldName: 'Pulau Langkah Pertama',
    worldColor: 'emerald',
    title: 'Jalan Berliku',
    description: 'Awas ada batu besar di depan! Belok kiri dan kanan untuk mencari jalan aman.',
    hint: 'Gunakan Belok Kiri atau Belok Kanan untuk menghindari batu hitam.',
    gridWidth: 5,
    gridHeight: 5,
    startPos: { x: 1, y: 3 },
    startDir: 'NORTH',
    targetPos: { x: 3, y: 1 },
    stars: [{ x: 1, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 2 }],
    obstacles: [{ x: 1, y: 1 }, { x: 2, y: 3 }],
    maxBlocks: 8,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
  },
  {
    id: 4,
    worldId: 1,
    worldName: 'Pulau Langkah Pertama',
    worldColor: 'emerald',
    title: 'Lompatan Hebat',
    description: 'Ada batu di tengah jalan! Pakai balok "Lompat" untuk melompati batu!',
    hint: 'Maju, lalu gunakan balok "Lompat" untuk melewati batu di depanmu.',
    gridWidth: 5,
    gridHeight: 5,
    startPos: { x: 2, y: 4 },
    startDir: 'NORTH',
    targetPos: { x: 2, y: 1 },
    stars: [{ x: 2, y: 3 }],
    obstacles: [{ x: 2, y: 2 }],
    maxBlocks: 5,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP'],
  },

  // PULAU 2: LINGKARAN AJAIB (Perulangan / Loop)
  {
    id: 5,
    worldId: 2,
    worldName: 'Pulau Lingkaran Ajaib',
    worldColor: 'amber',
    title: 'Perulangan Ajaib',
    description: 'Daripada memasang Maju berkali-kali, gunakan balok "Ulangi (Loop)"!',
    hint: 'Pakai balok Ulangi 3x dan isi dengan perintah Maju agar kodemu ringkas dan rapi.',
    gridWidth: 5,
    gridHeight: 5,
    startPos: { x: 2, y: 4 },
    startDir: 'NORTH',
    targetPos: { x: 2, y: 0 },
    stars: [{ x: 2, y: 3 }, { x: 2, y: 2 }, { x: 2, y: 1 }],
    obstacles: [{ x: 1, y: 2 }, { x: 3, y: 2 }],
    maxBlocks: 3,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'LOOP'],
  },
  {
    id: 6,
    worldId: 2,
    worldName: 'Pulau Lingkaran Ajaib',
    worldColor: 'amber',
    title: 'Pola Tangga Ajaib',
    description: 'Bantu Kiko menaiki tangga zig-zag menggunakan pola yang berulang!',
    hint: 'Perhatikan pola berulang: Maju -> Belok Kanan -> Maju -> Belok Kiri. Ulangi 2 kali!',
    gridWidth: 5,
    gridHeight: 5,
    startPos: { x: 1, y: 4 },
    startDir: 'NORTH',
    targetPos: { x: 3, y: 2 },
    stars: [{ x: 2, y: 3 }, { x: 3, y: 3 }],
    obstacles: [{ x: 1, y: 3 }, { x: 2, y: 4 }],
    maxBlocks: 6,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'LOOP'],
  },
  {
    id: 7,
    worldId: 2,
    worldName: 'Pulau Lingkaran Ajaib',
    worldColor: 'amber',
    title: 'Keliling Lapangan Bintang',
    description: 'Kumpulkan semua bintang di 4 sudut lapangan kotak!',
    hint: 'Pola keliling: Maju 2x lalu Belok Kanan. Ulangi pola ini 4 kali!',
    gridWidth: 5,
    gridHeight: 5,
    startPos: { x: 1, y: 3 },
    startDir: 'NORTH',
    targetPos: { x: 1, y: 3 },
    stars: [{ x: 1, y: 1 }, { x: 3, y: 1 }, { x: 3, y: 3 }],
    obstacles: [{ x: 2, y: 2 }],
    maxBlocks: 6,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'LOOP'],
  },
  {
    id: 8,
    worldId: 2,
    worldName: 'Pulau Lingkaran Ajaib',
    worldColor: 'amber',
    title: 'Rintangan Berturut-turut',
    description: 'Ada serangkaian batu berjarak. Lompat dan melangkah dengan lincah!',
    hint: 'Gunakan kombinasi Lompat dan Maju di dalam putaran Loop!',
    gridWidth: 6,
    gridHeight: 5,
    startPos: { x: 1, y: 3 },
    startDir: 'EAST',
    targetPos: { x: 5, y: 3 },
    stars: [{ x: 2, y: 3 }, { x: 4, y: 3 }],
    obstacles: [{ x: 2, y: 3 }, { x: 4, y: 3 }],
    maxBlocks: 4,
    availableBlocks: ['FORWARD', 'JUMP', 'LOOP'],
  },

  // PULAU 3: RINTANGAN CERDIK (Logika Petualang)
  {
    id: 9,
    worldId: 3,
    worldName: 'Pulau Rintangan Cerdik',
    worldColor: 'indigo',
    title: 'Menyeberang Sungai Biru',
    description: 'Hati-hati, ada petak air! Kiko harus melompatinya agar tidak basah.',
    hint: 'Air tidak bisa diinjak langsung, gunakan balok Lompat untuk melintasinya!',
    gridWidth: 5,
    gridHeight: 5,
    startPos: { x: 2, y: 4 },
    startDir: 'NORTH',
    targetPos: { x: 2, y: 0 },
    stars: [{ x: 2, y: 3 }, { x: 2, y: 1 }],
    obstacles: [],
    water: [{ x: 2, y: 2 }, { x: 1, y: 2 }, { x: 3, y: 2 }],
    maxBlocks: 6,
    availableBlocks: ['FORWARD', 'JUMP', 'TURN_RIGHT', 'TURN_LEFT', 'LOOP'],
  },
  {
    id: 10,
    worldId: 3,
    worldName: 'Pulau Rintangan Cerdik',
    worldColor: 'indigo',
    title: 'Kolektor Bintang Emas',
    description: 'Kumpulkan semua 3 bintang emas sebelum menuju bendera kemenangan.',
    hint: 'Petakan jalur terbaik dalam pikiranmu sebelum menyusun balok.',
    gridWidth: 6,
    gridHeight: 6,
    startPos: { x: 1, y: 4 },
    startDir: 'NORTH',
    targetPos: { x: 4, y: 1 },
    stars: [{ x: 1, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 3 }],
    obstacles: [{ x: 2, y: 3 }, { x: 3, y: 4 }, { x: 2, y: 1 }],
    maxBlocks: 10,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP', 'LOOP'],
  },
  {
    id: 11,
    worldId: 3,
    worldName: 'Pulau Rintangan Cerdik',
    worldColor: 'indigo',
    title: 'Labirin Pulau Kristal',
    description: 'Batu dan air menghalangi jalan. Temukan jalur alternatif yang cerdas!',
    hint: 'Jangan menyerah jika buntu, coba balikkan arah belok atau lompat rintangan!',
    gridWidth: 6,
    gridHeight: 6,
    startPos: { x: 1, y: 4 },
    startDir: 'NORTH',
    targetPos: { x: 4, y: 1 },
    stars: [{ x: 1, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 2 }],
    obstacles: [{ x: 1, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 4 }],
    water: [{ x: 2, y: 3 }, { x: 4, y: 4 }],
    maxBlocks: 12,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP', 'LOOP'],
  },
  {
    id: 12,
    worldId: 3,
    worldName: 'Pulau Rintangan Cerdik',
    worldColor: 'indigo',
    title: '🎓 Wisuda Programmer Cilik',
    description: 'Tantangan kelulusan! Gabungkan semua kemampuan logika, loop, dan navigasimu!',
    hint: 'Selesaikan tantangan ini untuk mencetak Sertifikat Programmer Cilik Resmi!',
    gridWidth: 6,
    gridHeight: 6,
    startPos: { x: 1, y: 5 },
    startDir: 'NORTH',
    targetPos: { x: 4, y: 0 },
    stars: [{ x: 1, y: 3 }, { x: 3, y: 3 }, { x: 4, y: 2 }],
    obstacles: [{ x: 2, y: 4 }, { x: 2, y: 1 }, { x: 3, y: 1 }],
    water: [{ x: 1, y: 2 }, { x: 3, y: 2 }],
    maxBlocks: 12,
    availableBlocks: ['FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP', 'LOOP'],
  },
];
